app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: "https://${BACKEND_HOST}"

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: "https://${BACKEND_HOST}"
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  csp:
#    connect-src: [ "'self'", 'http:', 'https:' ]
    script-src:
      - "'self'"
      - "'unsafe-eval'" # this is required for scaffolder usage, and ajv validation.
      - 'https://cdn.jsdelivr.net'
  reading:
    allow:
      - host: "${BACKEND_HOST}"
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  locations:
    - type: url
      target: "https://${BACKEND_HOST}/api/custom-entities/v1/entities.yaml"
      rules:
        - allow: [ User, Group, Component, System, API, Resource, Location ]

customEntities:
  allowGuest: true
  providers:
    googleGcs:
      bucket: telereso-docs
      folder: backstage/catalog
      name: custom-entities.yaml